name       : remmina
version    : 1.4.30
release    : 59
source     :
    - https://gitlab.com/Remmina/Remmina/-/archive/v1.4.30/Remmina-v1.4.30.tar.bz2 : b16d4eb4de4665f8f4d561e1d856d2b2e212c3ec9c652cd70827f2bba12f412a
license    :
    - GPL-2.0-or-later
    - OpenSSL
component  : network.util
summary    : Remmina GTK+ Remote Desktop Client
description: |
    Remmina is a remote desktop client written in GTK+, aiming to be useful for system administrators and travellers, who need to work with lots of remote computers in front of either large monitors or tiny netbooks. Remmina supports multiple network protocols in an integrated and consistant user interface. Currently RDP, VNC, NX, XDMCP and SSH are supported.
builddeps  :
    - pkgconfig(ayatana-appindicator3-0.1)
    - pkgconfig(freerdp2)
    - pkgconfig(libgcrypt)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsodium)
    - pkgconfig(libssh)
    - pkgconfig(libvncserver)
    - pkgconfig(python3)
    - pkgconfig(spice-client-gtk-3.0)
    - pkgconfig(vte-2.91)
    - pkgconfig(webkit2gtk-4.1)
setup      : |
    %cmake_ninja \
        -DWITH_AVAHI=OFF \
        -DWITH_CUPS=OFF \
        -DWITH_NEWS=OFF \
        -DWITH_TELEPATHY=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
