name       : remmina
version    : 1.4.8
release    : 38
source     :
    - https://gitlab.com/Remmina/Remmina/-/archive/v1.4.8/Remmina-v1.4.8.tar.gz : 4617f48c1b35335a6a0cc54962f8478f1ff22de553a81b2965764aaed577dbaf
license    :
    - GPL-2.0-or-later
    - OpenSSL
component  : network.util
summary    : Remmina GTK+ Remote Desktop Client
description: |
    Remmina is a remote desktop client written in GTK+, aiming to be useful for system administrators and travellers, who need to work with lots of remote computers in front of either large monitors or tiny netbooks. Remmina supports multiple network protocols in an integrated and consistant user interface. Currently RDP, VNC, NX, XDMCP and SSH are supported.
builddeps  :
    - pkgconfig(freerdp2)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libgcrypt)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsodium)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libssh)
    - pkgconfig(libvncserver)
    - pkgconfig(spice-client-gtk-3.0)
    - pkgconfig(vte-2.91)
    - pkgconfig(xkbfile)
setup      : |
    %cmake_ninja \
        -DWITH_AVAHI=OFF \
        -DWITH_APPINDICATOR=OFF \
        -DWITH_CUPS=OFF \
        -DWITH_MANPAGES=OFF \
        -DWITH_NEWS=OFF \
        -DWITH_TELEPATHY=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
