name       : remmina
version    : 1.4.16
release    : 45
source     :
    - https://gitlab.com/Remmina/Remmina/-/archive/v1.4.16/Remmina-v1.4.16.tar.bz2 : b0f181620420990f90aab384f698d7efb25ed92cf7ed4281861b920d510e6368
license    :
    - GPL-2.0-or-later
    - OpenSSL
component  : network.util
summary    : Remmina GTK+ Remote Desktop Client
description: |
    Remmina is a remote desktop client written in GTK+, aiming to be useful for system administrators and travellers, who need to work with lots of remote computers in front of either large monitors or tiny netbooks. Remmina supports multiple network protocols in an integrated and consistant user interface. Currently RDP, VNC, NX, XDMCP and SSH are supported.
builddeps  :
    - pkgconfig(freerdp2)
    - pkgconfig(libgcrypt)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsodium)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libssh)
    - pkgconfig(libvncserver)
    - pkgconfig(spice-client-gtk-3.0)
    - pkgconfig(vte-2.91)
    - pkgconfig(xkbfile)
setup      : |
    %cmake_ninja \
        -DWITH_AVAHI=OFF \
        -DWITH_APPINDICATOR=OFF \
        -DWITH_CUPS=OFF \
        -DWITH_NEWS=OFF \
        -DWITH_TELEPATHY=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
