name       : remmina
version    : 1.1.2
release    : 5
source     :
    - https://github.com/FreeRDP/Remmina/archive/v1.1.2.tar.gz : 2a075135e3c1a410ee0431f36a6795e2ac556b65fb82231e4126b5c372ca8cef
license    :
    - GPL-2.0
    - OpenSSL
component  : network.util
summary    : Remmina GTK+ Remote Desktop Client
description: |
    Remmina is a remote desktop client written in GTK+, aiming to be useful for
    system administrators and travellers, who need to work with lots of remote
    computers in front of either large monitors or tiny netbooks. Remmina supports
    multiple network protocols in an integrated and consistant user interface.
    Currently RDP, VNC, NX, XDMCP and SSH are supported.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(pango)
    - pkgconfig(atk)
    - gettext-devel
    - pkgconfig(gdk-x11-2.0)
    - pkgconfig(libssh)
    - pkgconfig(telepathy-glib)
    - pkgconfig(libvncserver)
    - pkgconfig(vte-2.91)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(xkbfile)
    - pkgconfig(freerdp)
setup      : |
    %patch -p1 <$pkgfiles/freerdp-1.2.patch
    %cmake -DWITH_AVAHI=OFF -DWITH_APPINDICATOR=OFF -DWITH_FREERDP=ON .
build      : |
    %make
install    : |
    %make_install
