name       : remmina
version    : 1.4.20
release    : 48
source     :
    - https://gitlab.com/Remmina/Remmina/-/archive/v1.4.20/Remmina-v1.4.20.tar.bz2 : 1778c6be04a45c67a5a825772d8491f1ed7b13c32f324aacb268f13d30b068a5
license    :
    - GPL-2.0-or-later
    - OpenSSL
component  : network.util
summary    : Remmina GTK+ Remote Desktop Client
description: |
    Remmina is a remote desktop client written in GTK+, aiming to be useful for system administrators and travellers, who need to work with lots of remote computers in front of either large monitors or tiny netbooks. Remmina supports multiple network protocols in an integrated and consistant user interface. Currently RDP, VNC, NX, XDMCP and SSH are supported.
builddeps  :
    - pkgconfig(appindicator-0.1)
    - pkgconfig(freerdp2)
    - pkgconfig(libgcrypt)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsodium)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libssh)
    - pkgconfig(libvncserver)
    - pkgconfig(spice-client-gtk-3.0)
    - pkgconfig(vte-2.91)
setup      : |
    %cmake_ninja \
        -DWITH_AVAHI=OFF \
        -DWITH_CUPS=OFF \
        -DWITH_NEWS=OFF \
        -DWITH_TELEPATHY=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
