name       : remmina
version    : 1.4.25
release    : 54
source     :
    - https://gitlab.com/Remmina/Remmina/-/archive/v1.4.25/Remmina-v1.4.25.tar.bz2 : 7c860c22b77b928fc93c5ab50cdb8af14a6a9160d17c548b9f084f66e634c9f2
license    :
    - GPL-2.0-or-later
    - OpenSSL
component  : network.util
summary    : Remmina GTK+ Remote Desktop Client
description: |
    Remmina is a remote desktop client written in GTK+, aiming to be useful for system administrators and travellers, who need to work with lots of remote computers in front of either large monitors or tiny netbooks. Remmina supports multiple network protocols in an integrated and consistant user interface. Currently RDP, VNC, NX, XDMCP and SSH are supported.
builddeps  :
    - pkgconfig(ayatana-appindicator3-0.1)
    - pkgconfig(freerdp2)
    - pkgconfig(libgcrypt)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsodium)
    - pkgconfig(libssh)
    - pkgconfig(libvncserver)
    - pkgconfig(spice-client-gtk-3.0)
    - pkgconfig(vte-2.91)
    - pkgconfig(webkit2gtk-4.0)
setup      : |
    %cmake_ninja \
        -DWITH_AVAHI=OFF \
        -DWITH_CUPS=OFF \
        -DWITH_NEWS=OFF \
        -DWITH_TELEPATHY=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
