name       : remmina
version    : 1.4.27
release    : 56
source     :
    - https://gitlab.com/Remmina/Remmina/-/archive/v1.4.27/Remmina-v1.4.27.tar.bz2 : 6e93f18a4930ca194d3651a7a0cedf1cf92e761884952d5651fc1e985daa9c5a
license    :
    - GPL-2.0-or-later
    - OpenSSL
component  : network.util
summary    : Remmina GTK+ Remote Desktop Client
description: |
    Remmina is a remote desktop client written in GTK+, aiming to be useful for system administrators and travellers, who need to work with lots of remote computers in front of either large monitors or tiny netbooks. Remmina supports multiple network protocols in an integrated and consistant user interface. Currently RDP, VNC, NX, XDMCP and SSH are supported.
builddeps  :
    - pkgconfig(ayatana-appindicator3-0.1)
    - pkgconfig(freerdp2)
    - pkgconfig(libgcrypt)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsodium)
    - pkgconfig(libssh)
    - pkgconfig(libvncserver)
    - pkgconfig(python3)
    - pkgconfig(spice-client-gtk-3.0)
    - pkgconfig(vte-2.91)
    - pkgconfig(webkit2gtk-4.0)
setup      : |
    %cmake_ninja \
        -DWITH_AVAHI=OFF \
        -DWITH_CUPS=OFF \
        -DWITH_NEWS=OFF \
        -DWITH_TELEPATHY=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
