name       : remmina
version    : 1.2.0_rc27
release    : 9
source     :
    - https://github.com/FreeRDP/Remmina/archive/v1.2.0-rcgit.27.tar.gz : 5f96fc2b1013a12acada30991ec7f46b53b731e71f735e662d830d9083db9826
license    :
    - GPL-2.0
    - OpenSSL
component  : network.util
summary    : Remmina GTK+ Remote Desktop Client
description: |
    Remmina is a remote desktop client written in GTK+, aiming to be useful for
    system administrators and travellers, who need to work with lots of remote
    computers in front of either large monitors or tiny netbooks. Remmina supports
    multiple network protocols in an integrated and consistant user interface.
    Currently RDP, VNC, NX, XDMCP and SSH are supported.
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(freerdp)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libssh)
    - pkgconfig(libvncserver)
    - pkgconfig(pango)
    - pkgconfig(spice-client-gtk-3.0)
    - pkgconfig(vte-2.91)
    - pkgconfig(xkbfile)
    - gettext-devel
setup      : |
    %cmake \
        -DWITH_AVAHI=OFF \
        -DWITH_APPINDICATOR=OFF \
        -DWITH_MANPAGES=OFF \
        -DWITH_TELEPATHY=OFF \
        .
build      : |
    %make
install    : |
    %make_install
    cd $installdir/usr/share/applications
    %patch < $pkgfiles/0001-Fix-pinning-to-taskbar.patch
