name       : remmina
version    : 1.2.31.2
release    : 17
source     :
    - git|https://gitlab.com/Remmina/Remmina.git: v1.2.31.2
license    :
    - GPL-2.0-or-later
    - OpenSSL
component  : network.util
summary    : Remmina GTK+ Remote Desktop Client
description: |
    Remmina is a remote desktop client written in GTK+, aiming to be useful for
    system administrators and travellers, who need to work with lots of remote
    computers in front of either large monitors or tiny netbooks. Remmina supports
    multiple network protocols in an integrated and consistant user interface.
    Currently RDP, VNC, NX, XDMCP and SSH are supported.
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(freerdp2)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libssh)
    - pkgconfig(libvncserver)
    - pkgconfig(pango)
    - pkgconfig(spice-client-gtk-3.0)
    - pkgconfig(vte-2.91)
    - pkgconfig(xkbfile)
setup      : |
    %cmake_ninja \
        -DWITH_AVAHI=OFF \
        -DWITH_APPINDICATOR=OFF \
        -DWITH_MANPAGES=OFF \
        -DWITH_TELEPATHY=OFF \
build      : |
    %ninja_build
install    : |
    %ninja_install
